// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package storagepacker is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Item
	BucketWrapper
	BucketV2
	Bucket
*/
package storagepacker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Item represents a entry that gets inserted into the storage packer
type Item struct {
	// ID is the UUID to identify the item
	ID string `sentinel:"" protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// message is the contents of the item
	Message *google_protobuf.Any `sentinel:"" protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetMessage() *google_protobuf.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type BucketWrapper struct {
	Data []byte `sentinel:"" protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size int64  `sentinel:"" protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *BucketWrapper) Reset()                    { *m = BucketWrapper{} }
func (m *BucketWrapper) String() string            { return proto.CompactTextString(m) }
func (*BucketWrapper) ProtoMessage()               {}
func (*BucketWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BucketWrapper) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BucketWrapper) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type BucketV2 struct {
	// Key is the storage path where the bucket gets stored
	Key string `sentinel:"" protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Buckets are the buckets contained within this bucket
	Buckets map[string]*BucketV2 `sentinel:"" protobuf:"bytes,3,rep,name=buckets" json:"buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ItemsMap holds the items contained within this bucket
	Items map[string]*Item `sentinel:"" protobuf:"bytes,4,rep,name=items" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// IsShard indicates if the bucket is pushed out of its parent bucket
	IsShard bool `sentinel:"" protobuf:"varint,5,opt,name=IsShard" json:"IsShard,omitempty"`
	// Depth indicates the hierarchical positioning of the bucket
	Depth int32 `sentinel:"" protobuf:"varint,6,opt,name=depth" json:"depth,omitempty"`
	// Size of the bucket in number of bytes
	Size int64 `sentinel:"" protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
}

func (m *BucketV2) Reset()                    { *m = BucketV2{} }
func (m *BucketV2) String() string            { return proto.CompactTextString(m) }
func (*BucketV2) ProtoMessage()               {}
func (*BucketV2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BucketV2) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BucketV2) GetBuckets() map[string]*BucketV2 {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *BucketV2) GetItems() map[string]*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *BucketV2) GetIsShard() bool {
	if m != nil {
		return m.IsShard
	}
	return false
}

func (m *BucketV2) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *BucketV2) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// Bucket is the entity that holds the packed items. It can
// contain multiple buckets within itself that gets sharded out
// when the bucket becomes big enough to not contain them all.
type Bucket struct {
	// Key is the storage path where the bucket gets stored
	Key string `sentinel:"" protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// For backwards compatibility
	Items []*Item `sentinel:"" protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *Bucket) Reset()                    { *m = Bucket{} }
func (m *Bucket) String() string            { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()               {}
func (*Bucket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Bucket) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Bucket) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "storagepacker.Item")
	proto.RegisterType((*BucketWrapper)(nil), "storagepacker.BucketWrapper")
	proto.RegisterType((*BucketV2)(nil), "storagepacker.BucketV2")
	proto.RegisterType((*Bucket)(nil), "storagepacker.Bucket")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xbb, 0xae, 0xf3, 0x6d, 0x13, 0x89, 0x03, 0xe3, 0x4e, 0xa5, 0x78, 0xa8, 0x07,
	0x33, 0x98, 0x07, 0x87, 0x07, 0x41, 0x61, 0xc2, 0x0e, 0x5e, 0x32, 0xd0, 0x73, 0xb6, 0xc6, 0xae,
	0xec, 0x47, 0x4b, 0x92, 0x09, 0xf5, 0x8f, 0x17, 0x69, 0xb2, 0xb8, 0x4d, 0xba, 0xdb, 0x4b, 0xf3,
	0x3e, 0x9f, 0xbe, 0xf7, 0x25, 0xd0, 0x56, 0x65, 0xc1, 0x25, 0x29, 0x44, 0xae, 0x72, 0xd4, 0x95,
	0x2a, 0x17, 0x2c, 0xe5, 0x05, 0x9b, 0x2f, 0xb9, 0xe8, 0x5f, 0xa7, 0x79, 0x9e, 0xae, 0xf8, 0x40,
	0x5f, 0xce, 0xb6, 0x9f, 0x03, 0xb6, 0x29, 0x4d, 0x67, 0xf4, 0x0a, 0x8d, 0x89, 0xe2, 0x6b, 0x74,
	0x0e, 0x6e, 0x96, 0x60, 0x27, 0x74, 0xe2, 0x33, 0xea, 0x66, 0x09, 0x22, 0x10, 0xac, 0xb9, 0x94,
	0x2c, 0xe5, 0xd8, 0x0d, 0x9d, 0xb8, 0x3d, 0xec, 0x11, 0x23, 0x21, 0x56, 0x42, 0x9e, 0x37, 0x25,
	0xb5, 0x4d, 0xd1, 0x03, 0x74, 0x5f, 0xb6, 0xf3, 0x25, 0x57, 0x1f, 0x82, 0x15, 0x05, 0x17, 0x08,
	0x41, 0x23, 0x61, 0x8a, 0x69, 0x65, 0x87, 0xea, 0xba, 0xfa, 0x26, 0xb3, 0x6f, 0x63, 0xf4, 0xa8,
	0xae, 0xa3, 0x1f, 0x17, 0x5a, 0x86, 0x7c, 0x1f, 0xa2, 0x0b, 0xf0, 0x96, 0xbc, 0xdc, 0x8d, 0x51,
	0x95, 0xe8, 0x09, 0x82, 0x99, 0xbe, 0x95, 0xd8, 0x0b, 0xbd, 0xb8, 0x3d, 0xbc, 0x21, 0x47, 0xbb,
	0x11, 0xcb, 0xee, 0x0a, 0x39, 0xde, 0x28, 0x51, 0x52, 0x0b, 0xa1, 0x11, 0xf8, 0x99, 0xe2, 0x6b,
	0x89, 0x1b, 0x9a, 0x8e, 0x4e, 0xd1, 0x55, 0x08, 0x3b, 0xd6, 0x00, 0x08, 0x43, 0x30, 0x91, 0xd3,
	0x05, 0x13, 0x09, 0xf6, 0x43, 0x27, 0x6e, 0x51, 0x7b, 0x44, 0x3d, 0xf0, 0x13, 0x5e, 0xa8, 0x05,
	0x6e, 0x86, 0x4e, 0xec, 0x53, 0x73, 0xf8, 0x5b, 0x2e, 0xd8, 0x2f, 0xd7, 0x9f, 0x42, 0xe7, 0x70,
	0xac, 0x9a, 0xfd, 0xee, 0xc0, 0xff, 0x62, 0xab, 0xad, 0x4d, 0xf9, 0xea, 0xc4, 0x7c, 0xd4, 0x74,
	0x3d, 0xba, 0x23, 0xa7, 0xff, 0x06, 0xb0, 0x9f, 0xb6, 0x46, 0x79, 0x7b, 0xac, 0xbc, 0xfc, 0xa7,
	0xac, 0xd8, 0x03, 0x5d, 0x34, 0x86, 0xa6, 0xf9, 0x4b, 0xbd, 0xca, 0xa4, 0xe7, 0xea, 0xf4, 0xea,
	0x55, 0xba, 0x63, 0xd6, 0xd4, 0xef, 0xe2, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xbe, 0x4e,
	0x88, 0x88, 0x02, 0x00, 0x00,
}
